---
abstract: 'high-performance tools for building search applications'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Search-Tools
no_index:
  directory:
    - t
    - inc
requires:
  Class::XSAccessor: '0.14'
  Data::Dump: '0'
  Encode: '0'
  Encoding::FixLatin: '0'
  File::Basename: '0'
  File::Slurp: '0'
  Moo: '0'
  Scalar::Util: '0'
  Search::Query: '0.300'
  Test::More: '0.94'
  namespace::sweep: '0'
  perl: '5.008003'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-Tools
  homepage: https://github.com/karpet/search-tools-perl
  license: http://dev.perl.org/licenses/
  repository: https://github.com/karpet/search-tools-perl
version: '1.000'
