--- #YAML:1.0
name:               Search-Tools
version:            0.67
abstract:           high-performance tools for building search applications
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:          0
    Encode:              0
    Encoding::FixLatin:  0
    File::Basename:      0
    File::Slurp:         0
    perl:                5.008003
    Rose::ObjectX::CAF:  0.03
    Scalar::Util:        0
    Search::Query:       0.18
    Test::More:          0.94
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-Tools
    homepage:    https://github.com/karpet/search-tools-perl
    license:     http://dev.perl.org/licenses/
    repository:  git@github.com:karpet/search-tools-perl.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
