# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Search-Tools
version:      0.14
version_from: lib/Search/Tools.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0.1
    Data::Dump:                    0
    Encode:                        0.1
    File::Slurp:                   0
    Search::QueryParser:           0.1
    Text::Aspell:                  0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
