--- #YAML:1.0
name:                Search-Tools
version:             0.12
abstract:            tools for building search applications
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0.1
    Data::Dump:                    0
    Encode:                        0.1
    Search::QueryParser:           0.1
    Text::Aspell:                  0.06
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    -  Peter Karman <perl@peknet.com>
