# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Search-Tools
version:      0.02
version_from: lib/Search/Tools.pm
installdirs:  site
requires:
    Encode:                        0.1
    Search::QueryParser:           0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
